---
- hosts: vlab
  tasks:
   - name: copy the patch scripts
     copy: src=/etc/ansible/ospatch_13042022.sh dest=/tmp/script1.sh
   - name: set permissions
     file: name=/tmp/script1.sh owner=root group=root mode=0755
   - name: executu the script
     shell: /bin/bash /tmp/script1.sh
